-- ModelOps Dashboard - initial schema (Phase 1)
-- Enum-typed columns are stored as VARCHAR (JPA EnumType.STRING).
-- Audit columns (created_at, updated_at, created_by, updated_by, version) are
-- populated by Spring Data JPA auditing on entities extending BaseAuditEntity.

-- ---------------------------------------------------------------------------
-- Roles & users
-- ---------------------------------------------------------------------------
CREATE TABLE roles (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(32) NOT NULL UNIQUE
);

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(64) NOT NULL UNIQUE,
    email         VARCHAR(128) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name  VARCHAR(128),
    enabled       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL,
    updated_at    TIMESTAMPTZ NOT NULL,
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255),
    version       BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

-- ---------------------------------------------------------------------------
-- Model registry
-- ---------------------------------------------------------------------------
CREATE TABLE model_formats (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type           VARCHAR(32) NOT NULL UNIQUE,
    display_name   VARCHAR(64) NOT NULL,
    file_extension VARCHAR(32),
    description    VARCHAR(256)
);

CREATE TABLE ai_models (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(128) NOT NULL,
    family            VARCHAR(96),
    provider          VARCHAR(96),
    modality          VARCHAR(32) NOT NULL,
    format_id         BIGINT NOT NULL REFERENCES model_formats (id),
    quantization      VARCHAR(32) NOT NULL,
    parameter_size    VARCHAR(32),
    estimated_vram_mb INTEGER,
    license           VARCHAR(96),
    source_url        VARCHAR(512),
    storage_note      VARCHAR(256),
    notes             VARCHAR(1024),
    status            VARCHAR(32) NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL,
    updated_at        TIMESTAMPTZ NOT NULL,
    created_by        VARCHAR(255),
    updated_by        VARCHAR(255),
    version           BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_ai_models_modality ON ai_models (modality);
CREATE INDEX idx_ai_models_status ON ai_models (status);
CREATE INDEX idx_ai_models_format ON ai_models (format_id);

-- ---------------------------------------------------------------------------
-- Hardware profiles
-- ---------------------------------------------------------------------------
CREATE TABLE hardware_profiles (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(128) NOT NULL,
    gpu_model        VARCHAR(128),
    vram_mb          INTEGER,
    ram_mb           INTEGER,
    backend_type     VARCHAR(32) NOT NULL,
    operating_system VARCHAR(96),
    driver_notes     VARCHAR(512),
    created_at       TIMESTAMPTZ NOT NULL,
    updated_at       TIMESTAMPTZ NOT NULL,
    created_by       VARCHAR(255),
    updated_by       VARCHAR(255),
    version          BIGINT NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------------------
-- Runtime backends
-- ---------------------------------------------------------------------------
CREATE TABLE runtime_backends (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(128) NOT NULL,
    backend_type VARCHAR(32) NOT NULL,
    status       VARCHAR(32) NOT NULL,
    endpoint_url VARCHAR(512),
    capabilities VARCHAR(512),
    description  VARCHAR(512),
    created_at   TIMESTAMPTZ NOT NULL,
    updated_at   TIMESTAMPTZ NOT NULL,
    created_by   VARCHAR(255),
    updated_by   VARCHAR(255),
    version      BIGINT NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------------------
-- Inference tasks
-- ---------------------------------------------------------------------------
CREATE TABLE inference_tasks (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id           BIGINT NOT NULL REFERENCES ai_models (id),
    runtime_backend_id BIGINT REFERENCES runtime_backends (id),
    status             VARCHAR(32) NOT NULL,
    prompt             VARCHAR(4096) NOT NULL,
    parameters         VARCHAR(2048),
    output_summary     VARCHAR(4096),
    latency_ms         BIGINT,
    tokens_per_second  DOUBLE PRECISION,
    error_message      VARCHAR(1024),
    started_at         TIMESTAMPTZ,
    finished_at        TIMESTAMPTZ,
    created_at         TIMESTAMPTZ NOT NULL,
    updated_at         TIMESTAMPTZ NOT NULL,
    created_by         VARCHAR(255),
    updated_by         VARCHAR(255),
    version            BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_inference_tasks_status ON inference_tasks (status);
CREATE INDEX idx_inference_tasks_created_at ON inference_tasks (created_at);

-- ---------------------------------------------------------------------------
-- Benchmark definitions (schema only in Phase 1)
-- ---------------------------------------------------------------------------
CREATE TABLE benchmark_definitions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(128) NOT NULL UNIQUE,
    type          VARCHAR(32) NOT NULL,
    description   VARCHAR(1024),
    scoring_notes VARCHAR(1024),
    created_at    TIMESTAMPTZ NOT NULL,
    updated_at    TIMESTAMPTZ NOT NULL,
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255),
    version       BIGINT NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------------------
-- Evaluation records (schema only in Phase 1)
-- ---------------------------------------------------------------------------
CREATE TABLE evaluation_records (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id            BIGINT NOT NULL REFERENCES ai_models (id),
    hardware_profile_id BIGINT REFERENCES hardware_profiles (id),
    runtime_backend_id  BIGINT REFERENCES runtime_backends (id),
    benchmark_id        BIGINT REFERENCES benchmark_definitions (id),
    status              VARCHAR(32) NOT NULL,
    latency_ms          BIGINT,
    tokens_per_second   DOUBLE PRECISION,
    memory_usage_mb     INTEGER,
    score               DOUBLE PRECISION,
    notes               VARCHAR(2048),
    created_at          TIMESTAMPTZ NOT NULL,
    updated_at          TIMESTAMPTZ NOT NULL,
    created_by          VARCHAR(255),
    updated_by          VARCHAR(255),
    version             BIGINT NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------------------
-- Tags (schema only in Phase 1)
-- ---------------------------------------------------------------------------
CREATE TABLE tags (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(64) NOT NULL UNIQUE,
    color       VARCHAR(16),
    description VARCHAR(256),
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL,
    created_by  VARCHAR(255),
    updated_by  VARCHAR(255),
    version     BIGINT NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------------------
-- Audit log (append-only)
-- ---------------------------------------------------------------------------
CREATE TABLE audit_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action      VARCHAR(32) NOT NULL,
    entity_type VARCHAR(64) NOT NULL,
    entity_id   VARCHAR(64),
    actor       VARCHAR(128) NOT NULL,
    detail      VARCHAR(512),
    created_at  TIMESTAMPTZ NOT NULL
);

-- ---------------------------------------------------------------------------
-- Seed canonical reference data (always applied)
-- ---------------------------------------------------------------------------
INSERT INTO roles (name) VALUES ('USER'), ('ADMIN');

INSERT INTO model_formats (type, display_name, file_extension, description) VALUES
    ('GGUF', 'GGUF', '.gguf', 'llama.cpp quantized format'),
    ('GGML', 'GGML', '.ggml', 'Legacy llama.cpp format'),
    ('ONNX', 'ONNX', '.onnx', 'Open Neural Network Exchange'),
    ('SAFETENSORS', 'Safetensors', '.safetensors', 'Safe tensor serialization'),
    ('PYTORCH', 'PyTorch', '.pt', 'PyTorch checkpoint'),
    ('TENSORFLOW', 'TensorFlow', '.pb', 'TensorFlow SavedModel'),
    ('OTHER', 'Other', NULL, 'Unspecified format');
