-- ModelOps Dashboard - Phase 2 schema (additive; never modify V1).
-- Adds DB-backed refresh tokens and tag association (join) tables.

-- ---------------------------------------------------------------------------
-- Refresh tokens (opaque, stored as SHA-256 hex; supports rotation + revocation)
-- ---------------------------------------------------------------------------
CREATE TABLE refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash VARCHAR(128) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_refresh_tokens_user ON refresh_tokens (user_id);

-- ---------------------------------------------------------------------------
-- Tag associations (many-to-many join tables)
-- ---------------------------------------------------------------------------
CREATE TABLE model_tags (
    model_id BIGINT NOT NULL REFERENCES ai_models (id) ON DELETE CASCADE,
    tag_id   BIGINT NOT NULL REFERENCES tags (id) ON DELETE CASCADE,
    PRIMARY KEY (model_id, tag_id)
);

CREATE TABLE benchmark_tags (
    benchmark_id BIGINT NOT NULL REFERENCES benchmark_definitions (id) ON DELETE CASCADE,
    tag_id       BIGINT NOT NULL REFERENCES tags (id) ON DELETE CASCADE,
    PRIMARY KEY (benchmark_id, tag_id)
);

CREATE TABLE task_tags (
    task_id BIGINT NOT NULL REFERENCES inference_tasks (id) ON DELETE CASCADE,
    tag_id  BIGINT NOT NULL REFERENCES tags (id) ON DELETE CASCADE,
    PRIMARY KEY (task_id, tag_id)
);

CREATE INDEX idx_model_tags_tag ON model_tags (tag_id);
CREATE INDEX idx_benchmark_tags_tag ON benchmark_tags (tag_id);
CREATE INDEX idx_task_tags_tag ON task_tags (tag_id);
